steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/veluchamy-flask-app:$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/veluchamy-flask-app:$COMMIT_SHA' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'compute'
  - 'instances'
  - 'update-container'
  - 'veluchamy-flask-instance'
  - '--zone'
  - '${_ZONE}'
  - '--container-image'
  - 'gcr.io/$PROJECT_ID/veluchamy-flask-app:$COMMIT_SHA'
substitutions:
    _ZONE: 'us-central1-a' #change if you used a different zone
options:
  logging: CLOUD_LOGGING_ONLY